### ISSUE TITLE
handle "No updates are to be performed" exception

### ISSUE THREAD

**Issue by oli99sc** [ImmobilienScout24/lambda-cloudformation-stack-updater#5]
There should be an sqs messages (or something else to inform caller) if cloudformation will not do any update because nothing is changed. Otherwise AWS Deployment notifier will wait forever.

No updates are to be performed. (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: ###): com.amazonaws.AmazonServiceException com.amazonaws.AmazonServiceException: No updates are to be performed. (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: ###) at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1181) at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:766) at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:485) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:306) at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:1270) at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.updateStack(AmazonCloudFormationClient.java:948) at is24.StackUpdateHandler$$anonfun$handler$4.apply(StackUpdateHandler.scala:42) at is24.StackUpdateHandler$$anonfun$handler$4.apply(StackUpdateHandler.scala:33) at scala.collection.immutable.List.foreach(List.scala:381) at is24.StackUpdateHandler.handler(StackUpdateHandler.scala:33) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by konz** [comment]
This will be an important feature of https://github.com/ImmobilienScout24/crassus that is currently in development
